name: Deploy React App to S3 and CloudFront

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (for building the React app)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Set Node.js version to 18.x

      # Step 3: Cache Node.js dependencies (optional)
      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install dependencies and build the React app
      - name: Install dependencies and build the React app
        run: |
          npm install  # Install dependencies
          npm run build  # Build the React app
          ls -al ./build  # List contents of build directory for debugging

      # Step 5: Deploy to S3
      - name: Deploy to S3
        run: |
          aws s3 sync $PWD/build/ s3://react1-s3-bucket --delete --region eu-north-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 6: Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E274GZPMVVLH7M --paths "/*" --region eu-north-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
