name: Build and Deploy to AWS S3

on:
  push:
    branches:
      - main  # You can modify this to match your production branch name

jobs:
  Build_Node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: |
          yarn install
          rm -rf ./dist    # Clear old build
          yarn build       # Generate the build in 'dist'

      - name: Check if dist folder exists
        run: |
          if [ ! -d "./dist" ]; then
            echo "Build failed. dist folder does not exist."
            exit 1
          fi

      - name: Check build folder (debugging)
        run: ls -al ./dist   # List the dist folder contents

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NODE_FILES
          path: ./dist    # Make sure you're uploading the correct directory

  Deploy_To_react2_S3:
    runs-on: ubuntu-latest
    needs: Build_Node    # Depends on successful completion of the Build_Node job
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: NODE_FILES
          path: ./dist    # Make sure you're downloading the correct artifact

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: aws s3 sync ./dist s3://react2-s3-bucket 

  Invalidate_Cloudfront_Cache:
    runs-on: ubuntu-latest
    needs: Deploy_To_react2_S3    # Depends on the Deploy_To_react2_S3 job
    steps:
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: "EE2PZ7411EKIW"    # CloudFront distribution ID
          PATHS: "/*"  # You can optimize this to only invalidate changed files
          AWS_REGION: eu-north-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
